import { FC, PropsWithChildren } from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import { Poppins } from 'next/font/google'
import Header from './Header'
import { ThemeProvider, createTheme } from '@mui/material'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
})

const theme = createTheme({
  typography: {
    fontFamily: poppins.style.fontFamily,
  },
  palette: {
    primary: {
      main: '#004A91',
    },
  },
})

const Main = styled.main.attrs({ className: poppins.className })`
  position: relative;
  min-height: 100vh;
`
const MainWrapper = styled.div`
  position: relative;
`

const ContentWrapper = styled.div`
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 10px;
  margin-block: 63px;
  margin-inline: 53px;
`

const Layout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Owis Capital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <ThemeProvider theme={theme}>
          <MainWrapper>
            <Header />
            <ContentWrapper>{children}</ContentWrapper>
          </MainWrapper>
        </ThemeProvider>
      </Main>
    </>
  )
}

export default Layout
